DROP TABLE IF EXISTS event_publication;


CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION
(
    ID                     VARCHAR(36) NOT NULL,
    LISTENER_ID            VARCHAR(512) NOT NULL,
    EVENT_TYPE             VARCHAR(512) NOT NULL,
    SERIALIZED_EVENT       VARCHAR(4000) NOT NULL,
    PUBLICATION_DATE       TIMESTAMP NOT NULL,
    COMPLETION_DATE        TIMESTAMP,
    STATUS                 VARCHAR(20),
    COMPLETION_ATTEMPTS    INTEGER,
    LAST_RESUBMISSION_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_BY_COMPLETION_DATE_IDX
    ON EVENT_PUBLICATION (COMPLETION_DATE);

CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION_ARCHIVE
(
    ID                     VARCHAR(36) NOT NULL,
    LISTENER_ID            VARCHAR(512) NOT NULL,
    EVENT_TYPE             VARCHAR(512) NOT NULL,
    SERIALIZED_EVENT       VARCHAR(4000) NOT NULL,
    PUBLICATION_DATE       TIMESTAMP NOT NULL,
    COMPLETION_DATE        TIMESTAMP,
    STATUS                 VARCHAR(20),
    COMPLETION_ATTEMPTS    INTEGER,
    LAST_RESUBMISSION_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_ARCHIVE_BY_COMPLETION_DATE_IDX
    ON EVENT_PUBLICATION_ARCHIVE (COMPLETION_DATE);
